function T_det = detectorTemp(T_det_i,T_TECc_i,T_frame,timeStep,...
    thermalMass, rStage,rInterface,heatLoad)

    T_det=T_det_i+(timeStep/thermalMass)*...
        ((T_frame-T_det_i)/rStage+(T_TECc_i-T_det_i)/rInterface+...
        heatLoad);

end